module.exports = {
  darkMode: ['class'],
  // v4 no necesita content, pero si querés forzar rutas, podés agregarlo.
  theme: {
    extend: {
      colors: {
        base: {
          black: 'hsl(var(--black))',
          white: 'hsl(var(--white))',
        },

        purple: {
          50: 'hsl(var(--purple-50))',
          100: 'hsl(var(--purple-100))',
          200: 'hsl(var(--purple-200))',
          300: 'hsl(var(--purple-300))',
          400: 'hsl(var(--purple-400))',
          500: 'hsl(var(--purple-500))',
          600: 'hsl(var(--purple-600))',
          700: 'hsl(var(--purple-700))',
          800: 'hsl(var(--purple-800))',
          900: 'hsl(var(--purple-900))',
          0: 'hsl(var(--purple-0))',
        },

        blue: {
          50: 'hsl(var(--blue-50))',
          100: 'hsl(var(--blue-100))',
          200: 'hsl(var(--blue-200))',
          300: 'hsl(var(--blue-300))',
          400: 'hsl(var(--blue-400))',
          500: 'hsl(var(--blue-500))',
          600: 'hsl(var(--blue-600))',
          700: 'hsl(var(--blue-700))',
          800: 'hsl(var(--blue-800))',
          900: 'hsl(var(--blue-900))',
          0: 'hsl(var(--blue-0))',
        },

        cyan: {
          50: 'hsl(var(--cyan-50))',
          100: 'hsl(var(--cyan-100))',
          200: 'hsl(var(--cyan-200))',
          300: 'hsl(var(--cyan-300))',
          400: 'hsl(var(--cyan-400))',
          500: 'hsl(var(--cyan-500))',
          600: 'hsl(var(--cyan-600))',
          700: 'hsl(var(--cyan-700))',
          800: 'hsl(var(--cyan-800))',
          900: 'hsl(var(--cyan-900))',
          0: 'hsl(var(--cyan-0))',
        },

        green: {
          50: 'hsl(var(--green-50))',
          100: 'hsl(var(--green-100))',
          200: 'hsl(var(--green-200))',
          300: 'hsl(var(--green-300))',
          400: 'hsl(var(--green-400))',
          500: 'hsl(var(--green-500))',
          600: 'hsl(var(--green-600))',
          700: 'hsl(var(--green-700))',
          800: 'hsl(var(--green-800))',
          900: 'hsl(var(--green-900))',
          0: 'hsl(var(--green-0))',
        },

        neutral: {
          50: 'hsl(var(--neutral-50))',
          100: 'hsl(var(--neutral-100))',
          200: 'hsl(var(--neutral-200))',
          300: 'hsl(var(--neutral-300))',
          400: 'hsl(var(--neutral-400))',
          500: 'hsl(var(--neutral-500))',
          600: 'hsl(var(--neutral-600))',
          700: 'hsl(var(--neutral-700))',
          800: 'hsl(var(--neutral-800))',
          900: 'hsl(var(--neutral-900))',
          0: 'hsl(var(--neutral-0))',
        },

        red: {
          50: 'hsl(var(--red-50))',
          100: 'hsl(var(--red-100))',
          200: 'hsl(var(--red-200))',
          300: 'hsl(var(--red-300))',
          400: 'hsl(var(--red-400))',
          500: 'hsl(var(--red-500))',
          600: 'hsl(var(--red-600))',
          700: 'hsl(var(--red-700))',
          800: 'hsl(var(--red-800))',
          900: 'hsl(var(--red-900))',
          0: 'hsl(var(--red-0))',
        },

        yellow: {
          50: 'hsl(var(--yellow-50))',
          100: 'hsl(var(--yellow-100))',
          200: 'hsl(var(--yellow-200))',
          300: 'hsl(var(--yellow-300))',
          400: 'hsl(var(--yellow-400))',
          500: 'hsl(var(--yellow-500))',
          600: 'hsl(var(--yellow-600))',
          700: 'hsl(var(--yellow-700))',
          800: 'hsl(var(--yellow-800))',
          900: 'hsl(var(--yellow-900))',
          0: 'hsl(var(--yellow-0))',
        },

        /* ===== tokens semánticos ===== */
        background: {
          'primary-default': 'hsl(var(--background-color-primary-default))',
          'accent-default-3': 'hsl(var(--background-color-accent-default-3))',
          'error-default-4': 'hsl(var(--background-color-error-default-4))',
          'info-default-6': 'hsl(var(--background-color-info-default-6))',
          'secondary-default-2':
            'hsl(var(--background-color-secondary-default-2))',
          'success-default-5': 'hsl(var(--background-color-success-default-5))',
        },
        border: {
          'primary-default': 'hsl(var(--border-color-primary-default))',
          'accent-default-3': 'hsl(var(--border-color-accent-default-3))',
          'error-default-4': 'hsl(var(--border-color-error-default-4))',
          'info-default-6': 'hsl(var(--border-color-info-default-6))',
          'secundry-default-2': 'hsl(var(--border-color-secundry-default-2))',
          'success-default-5': 'hsl(var(--border-color-success-default-5))',
        },
        text: {
          'accent-default-3': 'hsl(var(--text-color-accent-default-3))',
          'error-default-4': 'hsl(var(--text-color-error-default-4))',
          'link-default-6': 'hsl(var(--text-color-link-default-6))',
          'primary-default': 'hsl(var(--text-color-primary-default))',
          'secondary-default-2': 'hsl(var(--text-color-secondary-default-2))',
          'success-default-5': 'hsl(var(--text-color-success-default-5))',
          // disabled
          'accent-disabled': 'hsl(var(--text-color-accent-disabled))',
          'error-disabled': 'hsl(var(--text-color-error-disabled))',
          'link-disabled': 'hsl(var(--text-color-link-disabled))',
          'primary-disabled': 'hsl(var(--text-color-primary-disabled))',
          'secondary-disabled': 'hsl(var(--text-color-secondary-disabled))',
          'success-disabled': 'hsl(var(--text-color-success-disabled))',
        },
        icon: {
          'accent-default-3': 'hsl(var(--icon-color-accent-default-3))',
          'error-default-4': 'hsl(var(--icon-color-error-default-4))',
          'link-default-6': 'hsl(var(--icon-color-link-default-6))',
          'primary-default': 'hsl(var(--icon-color-primary-default))',
          'secondary-default-2': 'hsl(var(--icon-color-secondary-default-2))',
          'success-default-5': 'hsl(var(--icon-color-success-default-5))',
          // disabled
          'accent-disabled': 'hsl(var(--icon-color-accent-disabled))',
          'error-disabled': 'hsl(var(--icon-color-error-disabled))',
          'link-disabled': 'hsl(var(--icon-color-link-disabled))',
          'primary-disabled': 'hsl(var(--icon-color-primary-disabled))',
          'secondary-disabled': 'hsl(var(--icon-color-secondary-disabled))',
          'success-disabled': 'hsl(var(--icon-color-success-disabled))',
        },
      },
    },
  },
  plugins: [],
}
